name: macOS User info

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Generate
        id: dupa
        run: |
          echo "::set-output name=verden::[{ 'a': 'b'}]"
        
      - run: echo "${{fromJson(steps.dupa.outputs.verden).a}}"
