name: macOS User info

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Generate
        id: dupa
        run: |
          echo "::set-output name=verden::[{ 'a': 'b'}]"
        
      - run: |
          $jsonArrayString = "[`"test1:test2:test3`",`"test4:test5:test6`"]"
          echo "JSON_ARRAY=${jsonArrayString}" >> $GITHUB_OUTPUT

      - run: echo "${{fromJson(steps.dupa.outputs.verden).a}}"
